language: android
jdk: oraclejdk8
sudo: required

before_install:
    #- chmod +x gradlew

android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-25.0.0
    - android-25
    
notifications:
  email: false
  
script: ./gradlew build
